variable "allocated_storage" {}
variable "db_name" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "family" {}
variable "env" {}
variable "project_name" {}
variable "kms_key_id" {}
variable "subnets_ids" {}
variable "vpc_id" {}
variable "sg_cidr_blocks" {}
